WebApplication3/Models/ErrorViewModel.cs
namespace WebApplication3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication3/Models/UserInfo.cs
namespace WebApplication3.Models
{
    public class UserInfo
    {
        public string Name { get; set; } = "";
        public string Surname { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;

    }
}

WebApplication3/Models/UserModel.cs
namespace WebApplication3.Models
{
    public class User
    {
        public Guid UserPublicId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Age { get; set; }
        public List<string> Vlastnosti { get; set; } = new List<string>(); 
    }
}

WebApplication3/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication3/Controllers/UlohyController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Models;
namespace WebApplication3.Controllers
{
    public class UlohyController : Controller
    {
        public IActionResult uloha1()
        {
            return View();
        }
        public IActionResult uloha2()
        {
            return View();
        }
        public IActionResult uloha3()
        {
            return View();
        }
        public IActionResult uloha4()
        {
            var userList = new List<UserInfo>()
            {
                new UserInfo
                {
                    Name="Test",
                    Surname="Test",
                    Email="test@gmail.com",
                },
                new UserInfo
                {
                    Name = "Jozef",
                    Surname="Mrkvička",
                    Email = "jozef@gmail.com",
                } };
            return View(userList);
        }
        public IActionResult uloha5()
        {
            var userList = new List<UserInfo>()
            {
                new UserInfo
                {
                    Name="Test",
                    Surname="Test",
                    Email="test@gmail.com",
                },
                new UserInfo
                {
                    Name = "Jozef",
                    Surname="Mrkvička",
                    Email = "jozef@gmail.com",
                } };
            return View(userList);
        }
        public IActionResult uloha6()
        {
            return View();
        }
        public IActionResult uloha7()
        {
            return View();
        }
        public IActionResult uloha8()
        {
            return View();
        }
        public IActionResult uloha9()
        {
            return View();
        }
        private static List<User> users = new List<User>();

        [HttpGet]
        public IActionResult LoginForm()
        {
            return View(new User());
        }

        [HttpPost]
        public IActionResult LoginForm(User model)
        {
            var user = new User()
            {
                UserPublicId = Guid.NewGuid(),
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                Age = model.Age,
                Password = model.Password,
                Vlastnosti = model.Vlastnosti
            };
            users.Add(user);
            ViewBag.Users = users;
            return View("Register", user);
        }
    }
}

WebApplication3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="uloha1">Uloha1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="uloha2">Uloha2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="uloha3">Uloha3</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="uloha4">Uloha4</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="uloha5">Uloha5</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="uloha6">Uloha6</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="uloha7">Uloha7</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="uloha8">Uloha8</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulohy" asp-action="LoginForm">LoginForm</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication3/Views/Ulohy/LoginForm.cshtml
<h1>Login</h1>
<div id="loginForm">
    <form method="post" asp-controller="Ulohy" asp-action="LoginForm">
        <input type="text" name="FirstName" placeholder="FirstName" required />
        <input type="text" name="LastName" placeholder="LastName" required />
        <input type="email" name="Email" placeholder="Email" required />
        <input type="number" name="Age" placeholder="Age" required />
        <input type="password" name="Password" placeholder="Password" required />
		<input id="todoitem" type="text" name="ToDoList" placeholder="ToDoList" />
        <input id="hidden" type="hidden" name="List" placeholder="List" />  
        <button type="button" id="pridaj"> + </button>
		<div id="todoItems">
			<p>To Do Items:</p>
        </div>
        <button type="submit">Login</button>
    </form>
</div>

<script>
      const Vlastnosti=[];
      var button=document.getElementById("pridaj");
      button.addEventListener("click", function() {
      newitem=document.getElementById("todoitem").value;
	  Vlastnosti.push(newitem);
	  var item=document.createElement("p");
      item.textContent=newitem;
      document.getElementById("todoItems").appendChild(item);
	  document.getElementById("todoitem").value="";
    });
	    var form=document.getElementById("loginForm");
		  form.addEventListener("submit", function() {
		  document.getElementById("hidden").value=Vlastnosti;
		  });
	  
</script>

WebApplication3/Views/Ulohy/Register.cshtml
@model WebApplication3.Models.User

<div> First name: @Model.FirstName</div>
<div> Last name: @Model.LastName</div>
<div> Email: @Model.Email</div>
<div> Age: @Model.Age</div>
<div> Password: @Model.Password</div>

	@foreach (var user in @Model.Vlastnosti)
	{
			<div> @user</div>
	}

WebApplication3/Views/Ulohy/_UserCard.cshtml
@model UserInfo
<div class="card"> 
    <img src="~/images/5b165ce11ae66224008b4b92.webp" alt="huhu" />
    <div class="card-text">
        <h1>@Model.Name @Model.Surname</h1>
        <p>@Model.Email</p>
    </div>
</div>

WebApplication3/Views/Ulohy/uloha1.cshtml
<head>
	<link rel="stylesheet" href="~/css/uloha1.css"/>
</head>
<div class="center-container">
    <h1 class="display-4">Vitaj na stránke</h1>
    <p>Tato stranka je jednoducha</p>
    <a href="/" class="btn-primary">Späť na web</a>
</div>

WebApplication3/Views/Ulohy/uloha2.cshtml
<head>
	<link rel="stylesheet" href="~/css/uloha2.css" />
</head>
<div class="card"><img src="~/images/5b165ce11ae66224008b4b92.webp" alt="" />
<h1><b>Ján Novák</b></h1>
<p>Frontend Developer</p>
<a href="/" class="btn-primary">Späť na web</a>
</div>

WebApplication3/Views/Ulohy/uloha3.cshtml
<head>
	<link rel="stylesheet" href="~/css/uloha3.css" />
</head>
<div class="grid">
@for (int i = 1; i <= 6; i++)
{
	<div class="card">
		<img src="~/images/5b165ce11ae66224008b4b92.webp" alt="" />
		<h1><b>Ján Novák</b></h1>
		<p>Frontend Developer</p>
		<a href="/" class="btn-primary">Späť na web</a>
	</div>
}
</div>

WebApplication3/Views/Ulohy/uloha4.cshtml
<head>
	<link rel="stylesheet" href="~/css/uloha4.css"/>
</head>
<div class="text-center">
	<table>
		<tr>
			<th>Meno</th>
			<th>Priezvisko</th>
			<th>Email</th>
		</tr>
	@foreach(var user in Model){
		<tr>
		<td>@user.Name</td>
		<td>@user.Surname</td>
		<td>@user.Email</td>
		</tr>
	}
	</table>
</div>

WebApplication3/Views/Ulohy/uloha5.cshtml
<head>
	<link rel="stylesheet" href="~/css/uloha5.css" />
</head>
@model List<UserInfo>
<div class="grid">
	@foreach(var user in Model){
		<partial name="_UserCard" model="user" />
	}
</div>

WebApplication3/Views/Ulohy/uloha6.cshtml
<head>
	<link rel="stylesheet" href="~/css/uloha5.css" />
</head>
<div>
	<h1>Toggle textu</h1>
	<p>Tento text sa má skrývať a zobrazovať</p>
	<button onclick="zobraz()">Zobraziť/Skryť</button>
</div>

WebApplication3/Views/Ulohy/uloha7.cshtml
<head>
	<link rel="stylesheet" href="~/css/uloha5.css" />
</head>
<div class="clickcard" id="clickcard">
	<p>Počet kliknutí: <span class="totalklik">0</span></p>
	<button onclick="klik()">Klikni</button>
</div>

WebApplication3/Views/Ulohy/uloha8.cshtml
<head>
	<link rel="stylesheet" href="~/css/uloha5.css" />
</head>
<p>Správa min 20 znakov:</p>
<textarea id="Textbox">
</textarea>